<?php

declare(strict_types=1);

/**
 * @file
 * Install, update and uninstall functions for the employee module.
 */

/**
 * Implements hook_install().
 */
function employee_install(): void {
  \Drupal::messenger()->addStatus(t('Module employee has been installed.'));
}

/**
 * Implements hook_uninstall().
 */
function employee_uninstall(): void {
  \Drupal::messenger()->addStatus(t('Module employee has been uninstalled.'));
}
